"""Hardcoded PT-BR crisis response messages for TheraFlow.

These constants are NEVER generated by an LLM.  They contain fixed, reviewed
text that must be shown verbatim whenever the safety detector flags a message
as medium- or high-risk.

Usage::

    from theraflow.safety.responses import CRISIS_MESSAGE_HIGH, CRISIS_MESSAGE_MEDIUM

    risk = detect_risk(user_text)
    if risk.risk_level == "high":
        send(CRISIS_MESSAGE_HIGH)
    elif risk.risk_level == "medium":
        send(CRISIS_MESSAGE_MEDIUM)

Emergency contacts embedded in these messages:
  - CVV (Centro de Valorização da Vida): 188  — 24 h, gratuito
  - SAMU (Serviço de Atendimento Móvel de Urgência): 192
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# High-risk response
# Shown when the detector returns risk_level == "high".
# ---------------------------------------------------------------------------

CRISIS_MESSAGE_HIGH: str = (
    "Percebo que você está passando por um momento muito difícil, e me importo "
    "com o que você está sentindo.\n\n"
    "Por favor, entre em contato agora com um serviço de emergência:\n\n"
    "📞 *CVV — Centro de Valorização da Vida*: ligue *188* (24 h, gratuito)\n"
    "🚑 *SAMU*: ligue *192*\n\n"
    "⚠️ Este bot não substitui atendimento emergencial. Se você ou alguém "
    "estiver em perigo imediato, ligue agora — há pessoas prontas para ajudar."
)

# ---------------------------------------------------------------------------
# Medium-risk response
# Shown when the detector returns risk_level == "medium".
# ---------------------------------------------------------------------------

CRISIS_MESSAGE_MEDIUM: str = (
    "Entendo que você está enfrentando uma situação difícil, e estou aqui com "
    "você.\n\n"
    "Conversar com um profissional de saúde mental pode fazer muita diferença. "
    "Se precisar de apoio agora, o CVV oferece escuta gratuita a qualquer hora:\n\n"
    "📞 *CVV — Centro de Valorização da Vida*: ligue *188* (24 h, gratuito)\n\n"
    "Você pode continuar nossa conversa quando quiser — não precisa passar por "
    "isso sozinho(a)."
)
